### ISSUE TITLE
Android error: OPENSSL_internal:BAD_DECRYPT

### ISSUE THREAD

**Issue by jopmiddelkamp** [jeroentrappers/flutter_keychain#37]
Get this error for some of my Android users.

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(flutter_keychain, error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT, javax.crypto.BadPaddingException: error:1e000065:Cipher functions:OPENSSL_internal:BAD_DECRYPT
	at com.android.org.conscrypt.NativeCrypto.EVP_CipherFinal_ex(Native Method)
	at com.android.org.conscrypt.OpenSSLEvpCipher.doFinalInternal(OpenSSLEvpCipher.java:152)
	at com.android.org.conscrypt.OpenSSLCipher.engineDoFinal(OpenSSLCipher.java:374)
	at javax.crypto.Cipher.doFinal(Cipher.java:2056)
	at d0.a.b(Unknown Source:40)
	at d0.b.onMethodCall(Unknown Source:181)
	at v4.k$a.a(Unknown Source:17)
	at i4.c.l(Unknown Source:18)
	at i4.c.m(Unknown Source:40)
	at i4.c.i(Unknown Source:0)
	at i4.b.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:978)
	at android.os.Handler.dispatchMessage(Handler.java:104)
	at android.os.Looper.loopOnce(Looper.java:238)
	at android.os.Looper.loop(Looper.java:355)
	at android.app.ActivityThread.main(ActivityThread.java:8080)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1026)
, null). Error thrown PlatformException.
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
       at FlutterKeychain.get(flutter_keychain.dart:15)
       at ._getHydratedStorageEncryptionKey(bootstrap.dart:421)
       at ._getHydratedStorage(bootstrap.dart:409)
       at .bootstrap(bootstrap.dart:40)
       at .mainDelegate(main_delegate.dart:72)
```

This is the code
```dart
Future<Storage> _getHydratedStorage() async {
  var encryptionKey = await _getHydratedStorageEncryptionKey();
  final storage = await HydratedStorage.build(
    storageDirectory: await getTemporaryDirectory(),
    encryptionCipher: HydratedAesCipher(
      sha256.convert(utf8.encode(encryptionKey)).bytes,
    ),
  );
  return storage;
}

Future<String> _getHydratedStorageEncryptionKey() async {
  const storageKey = '...';
  var encryptionKey = await FlutterKeychain.get(
    key: storageKey,
  );
  if (encryptionKey == null) {
    encryptionKey = base64.encode(Hive.generateSecureKey());
    await FlutterKeychain.put(
      key: storageKey,
      value: encryptionKey,
    );
  }
  return encryptionKey;
}
```

And this is the version of the package.
```yaml
environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_keychain: ^2.2.1
```

**Comment by jopmiddelkamp** [comment]
Got him to reset the storage of the app and now it works. Might somehow got corrupted.

**Comment by jeroentrappers** [comment]
Thanks

**Comment by jopmiddelkamp** [comment]
Do you have any suggestions to address this issue? It’s occurring more frequently, and we believe it’s not ideal. Currently, we have to train our service desk to instruct users to clear their storage, which forces them to log back in. If this isn’t directly related to the problem they’re experiencing, it leads to a very poor user experience.

It would be great if we could prevent the app from getting into this problematic state. Do you have any insights or potential cause and/or solutions for this?

One of our team members with a Galaxy S23 Ultra encounters this issue more frequently, he says it happens sometimes after an app update when it is updated via the Play Store.

In our error logging we see more type of devices that:
<details>
  <summary>Show Devices</summary>
 - Galaxy A03 Core
 - Galaxy A13
 - Galaxy A35 5G
 - Galaxy J2 Core
 - Galaxy A02
 - Galaxy S24 Ultra
 - Galaxy S23 Ultra
 - Galaxy A10
 - Galaxy A04
 - Galaxy S23 FE
 - Galaxy A22 5G
 - Galaxy S20 FE
 - Galaxy A10
 - Galaxy A03s
 - Galaxy A12
 - Galaxy S23
 - Galaxy S22
 - Galaxy S24 FE
 - Galaxy A55 5G
 - Galaxy A14
 - Galaxy S21 FE 5G
 - Galaxy S10
 - Galaxy A55 5G
 - Galaxy A31
 - Galaxy A12
 - Galaxy S24+
 - Galaxy Z Fold6
 - Galaxy Z Flip3 5G
 - Galaxy A51
 - Galaxy A25 5G
 - Galaxy A05
 - Galaxy A03
 - Galaxy A02s
 - Moto G32
 - Moto G(7) Plus
 - Moto G24 Power
 - Moto G(9) Play
 - Moto E20
 - Moto E(7i) Power
 - Moto G41
 - Moto G24
 - Moto G23
 - Motorola Razr 40
 - Motorola One Hyper
 - Moto G22
 - Moto G04
 - Moto G(7) Power
 - Moto G85 5G
 - Motorola Edge 50 Pro
 - Moto G(60)s
 - Poco M6 Pro
 - Redmi Note 13
 - Redmi Note 12 Pro 5G
 - Redmi Note 11
 - Redmi Note 13 Pro
 - Redmi 14C
 - Redmi 10 2022
 - Redmi Note 13
 - Redmi 14C
 - Redmi Note 13 Pro 5G
 - Redmi 13C
 - Redmi 13C
 - Redmi Note 13 Pro+ 5G
 - Xiaomi 13 Ultra
 - Redmi Note 12S
 - Redmi 12C
 - Redmi Note 12 Pro+ 5G
 - Pixel 9
 - Pixel 8a
</details>

Looking forward to your thoughts!

**Comment by Tr736** [comment]
@jeroentrappers why is this issue closed?

I too am experiencing the same issues
